### ISSUE TITLE
Gerenciador de Comunicação

### ISSUE THREAD

**Issue by hlah** [hlah/dropfolder#2]

**Comment by hlah** [comment]
## Tipos de mensagem
- Nova conexão.
- Atualização de arquivo.
- Criação de arquivo.
- Remoção de arquivo.
- blablabla

**Comment by hlah** [comment]
Acho que temos que criar uma classe _Connection_ implementando o TCP usando o UDP.
Essa classe implementaria os métodos __send__ e __receive__ transmitindo dados de qualquer tamanho, sem perdas, em ordem, etc. que nem o TCP.

Também teríamos duas duas funções que retornam conexões:
- __listen__: espera por uma conexão, receberia porta a ser ouvida.
- __connect__: se conecta à um servidor, receberia o endereço e a porta.

Talvez teria que ter alguma forma de trocar a porta da conexão, para permitir que o servidor continue escutando por novas conexões enquanto uma (ou mais) conexões estão ativas.

Também temos que ver se cada uma das funções seriam bloqueantes ou não.

Dai em cima disso podemos construir os mecanismos de troca de arquivos e mensagens.

O que acha @ricardocoelho ?

**Comment by ricardocoelho** [comment]
> Talvez teria que ter alguma forma de trocar a porta da conexão, para permitir que o servidor continue escutando por novas conexões enquanto uma (ou mais) conexões estão ativas.

Não sei se eu entendi bem o que tu quis dizer, mas a princípio o servidor escuta em só uma porta.
Imagino que possa se criar uma nova thread pra processar cada pacote se tu quiser menos latência.


> Também temos que ver se cada uma das funções seriam bloqueantes ou não.

Acho q talvez antes disso aí, a gente deve especificar como vai ser o protocolo de comunicação, pois dependendo das caracteristicas se planeja se é melhor bloqueante ou não.



> Acho que temos que criar uma classe _Connection_ implementando o TCP usando o UDP.
> Essa classe implementaria os métodos **send** e **receive** transmitindo dados de qualquer tamanho, sem perdas, em ordem, etc. que nem o TCP.

Eu não sei o quão complexo precisa ser esse controle de transmissão. Talvez dê muito trabalho "implementar o TCP". De novo, talvez o protocolo não exija essa abstração de conexão.

> Dai em cima disso podemos construir os mecanismos de troca de arquivos e mensagens.

Se a gente definir meio por cima as informações que as nossas mensagens devem conter, fica mais fácil de especificar o protocolo.

**Comment by hlah** [comment]
> > Talvez teria que ter alguma forma de trocar a porta da conexão, para permitir que o servidor continue escutando por novas conexões enquanto uma (ou mais) conexões estão ativas.
> 
> Não sei se eu entendi bem o que tu quis dizer, mas a princípio o servidor escuta em só uma porta.
> Imagino que possa se criar uma nova thread pra processar cada pacote se tu quiser menos latência.

O que eu quis dizer é que para manter o servidor na escuta por novas conexões teria que passar as já estabelecidas para outras porta.
Mas isso assumindo que o servidor só pode manter uma conexão por porta.

> 
> > Também temos que ver se cada uma das funções seriam bloqueantes ou não.
> 
> Acho q talvez antes disso aí, a gente deve especificar como vai ser o protocolo de comunicação, pois dependendo das caracteristicas se planeja se é melhor bloqueante ou não.

Acho que dá para ir fazendo bloqueante, caso seja necessários adicionamos uma versão não bloqueante.

> 
> > Acho que temos que criar uma classe _Connection_ implementando o TCP usando o UDP.
> > Essa classe implementaria os métodos **send** e **receive** transmitindo dados de qualquer tamanho, sem perdas, em ordem, etc. que nem o TCP.
> 
> Eu não sei o quão complexo precisa ser esse controle de transmissão. Talvez dê muito trabalho "implementar o TCP". De novo, talvez o protocolo não exija essa abstração de conexão.
> 

Não seria implementar exatamente o TCP, só algo parecido: possuir conexões, não ter perdas, não ter limite de tamanho.

> > Dai em cima disso podemos construir os mecanismos de troca de arquivos e mensagens.
> 
> Se a gente definir meio por cima as informações que as nossas mensagens devem conter, fica mais fácil de especificar o protocolo.

É que eu imaginei só passar uma sequência de bytes e depois interpretar eles.
Também podemos já deixar estruturado, mas daí temos que definir já o que são as possíveis mensagens.
